kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: the-best-letter
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: the-best-letter
        role: backend
        env: production
    spec:
      containers:
      - name: the-best-letter
        image: PRODUCTION_IMAGE
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - name: backend
          containerPort: 8080
